export const homeobj1 = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Pronto',
    headLine: 'SignUp',
    description: 'Just one click away to explore a seamless experience', 
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/signup1.svg'),
    alt: 'Signup',
    dark: false,
    primary: false,
    darkText: true,
}